### PR TITLE
slight refactor to avoid so much serde work and more tests

### PR DESCRIPTION
**Pull request by selfup**
Just a slight refactor to avoid so much serde work

### CODE REVIEW

**Comment by selfup** [comment]
Travis seems to be failing to compile our repo with nightly? Hmm...

**Comment by selfup** [comment]
Tried to build on the new nightly (2016-06-20) that Travis pulled, and it failed locally. Went back to 2016-06-09 and it works fine. Seems that Serde is always a week behind.

Sean Griffin mentioned this with Diesel as well. He recommends using the previous weeks nightly.

**Comment by selfup** [comment]
Ok awesome. Travis built on 06-10. Going to upgrade to 06-15 

Built on 06-15. Back to normal. Will use VM in the future to test nightlies.

Wasn't sure how to specify versions on Travis.

Now I know haha

**Comment by selfup** [comment]
@cite-reader 
@pindell-matt 

Ok so you can indeed specify the nightly version with Travis CI, I'll use a local VM to test future versions, and then tell Travis which nightly to pull. Will also need to update Documentation often, but that's fine.

PR is ready to be merged

**Comment by selfup** [comment]
Seems pretty fast to me!

screenshot from 2016-06-23 00 19 33

**Comment by selfup** [comment]
### The slowest operation (out of three benchmarks) takes:

0.06634 milliseconds 

OR 

0.00006634 seconds 

### The fastest operation (out of three benchmarks) takes:

0.00138 milliseconds

OR

0.00000138 seconds

### On Linux

**Comment by pindell-matt** [comment]
Looks good to me!

**Pull request merged**
