### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by cite-reader**
Improved errors, tidied up features being asked for, taking string slices where possible.

Pulled the benchmark into its own function, and hooked the rustc-provided benchmark infrastructure. Run `cargo bench` to see that; I get 18,968 ns/iter, what do you get?

### CODE REVIEW

**Comment by selfup** [comment]
Thanks for the nice PR!

Really digging this so far. Thanks for cleaning things up!

Gonna wait for @pindell-matt to review this as well

**Comment by selfup** [comment]
I get `274,867 ns/iter (+/- 25,608)` on Windows. Let me check on OSX

**Comment by selfup** [comment]
Which rust nightly are you running? My build fails on OSX with `rustup override add nightly-2016-05-30`

**Comment by selfup** [comment]
I keep failing on aster. 

I uninstalled rust. This problem occurs on this repo now for OSX.

Reinstalling using rustup. 

Will poke around

**Comment by selfup** [comment]
Ok got it running on: `rustc 1.11.0-nightly (5c2a5d449 2016-06-11)`

Woowoo

**Comment by selfup** [comment]
208,157 ns/iter (+/- 62,297) on OSX 2015 MBP i5 8GB RAM

What kind of rig are you running?

My Windows rig has an i5 6600k at 4.3Ghz. Just wondering how you are getting such amazing performance per iter

**Comment by selfup** [comment]
I'll run this on Ubuntu 14.04 and Fedora 23 on a three year old ASUS laptop with an i7.

Darwin already ran faster on the iters compared to W10. I am sure Linux will have better results

**Comment by pindell-matt** [comment]
Sorry for the delay - this all looks great, merging now.

**Comment by cite-reader** [comment]
I have a recent Thinkpad with an i7 processor... and _no spinning disks_ whatsoever. The solid-state hard drive probably has a bit of an effect on filesystem performance.

**Pull request merged**
