### PR TITLE
Added base contributing Document

### LINKED ISSUE #14: Write a Contribution Template
We will need to write a contribution template similar to [this one](https://github.com/selfup/stringer/blob/master/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by selfup**
Added a base `CONTRIBUTING.md` document. This way there are guidelines for any new contributors!

This closes #14

### CODE REVIEW

**Comment by selfup** [comment]
Added a Vagrantfile example for Windows users. 

If contributors follow this, we won't have to force Travis CI to build for Windows users to find out if their build/test-suite passes on *nix.

**Comment by selfup** [comment]
Removed allowed failures on Travis for nightly. Added more concise instructions in `CONTRIBUTING.md`.

**Comment by selfup** [comment]
Needed to add the `test2` file in the `db` dir for the tests to pass since it was in the `.gitignore`.

**Comment by selfup** [comment]
By telling the `.gitignore` to ignore everything in the `db` dir, but the test2 file, we will not have a cluttered Environment when pulling down. 

But we will have the needed dir/file to make Travis CI happy!

**Comment by pindell-matt** [comment]
Looks great!

**Pull request merged**
